### PR TITLE
add plugins that enable publishing to sonatype

### PR DESCRIPTION
**Pull request by lucastorri**
I'm moving a step back from `sbt-release` and just using what I was used to: gpg + sonatype plugins.

http://central.maven.org/maven2/com/unstablebuild/slime_2.12/0.2.0/

This requires a few manual steps and my GPG credentials. We can figure out a better way later, but I wanted to get this out of the door.

### CODE REVIEW

**Comment by hcwilhelm** [comment]
Are you just more comfortable with gpg + sonatype or what is the reason to move away from sbt-release ? Otherwise I think it's fine as long as the artifakt gets uploaded :)

**Comment by hcwilhelm** [comment]
Also Looks like you have to run scalafmt to please travis

**Review by hcwilhelm — APPROVED** [review]

**Comment by lucastorri** [comment]
It's the one I know already. `sbt-release` can be used in conjunction with these, but due to lack of time, I'd rather don't do the integration right now.

**Comment by hansjoergschurr** [comment]
Go for it and thanks for pushing that forward. It was somewhere on the back of my mind, but since I don't work with Scala anymore and don't have a anything related to it installed right now it rotted on  my TODO list.

**Pull request merged**
